AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4
  Exclude:
    - bin/*

# And/Or is actually quite cool. But they shouldn't be used as && - ||
# Read about it: http://www.virtuouscode.com/2010/08/02/using-and-and-or-in-ruby/
# Using 'and' at the right place makes for some sexy, readable code.
AndOr:
  Enabled: false

# Double negation ain't bad, it's used in numerous languages.
# Sometimes you really do want the boolean value of a variable
Style/DoubleNegation:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 110

Metrics/ClassLength:
  Enabled: true
  Max: 130

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

# Disabling because it causes false positives
Layout/EmptyLinesAroundArguments:
  Enabled: false
